### ISSUE TITLE
Need more runs of each

### ISSUE THREAD

**Issue by Pebaz** [dullbananas/nimporter-vs-cython#1]
Since a lot of things can get cached after an initial run, try putting a for loop that executes each function 1000 times or so in the times block.
This will give additional info.
Additionally, you could average the runtimes of each invocation over 1000 runs to reduce the effect of minimums and maximums.

**Comment by dullbananas** [comment]
not sure i understand what you exactly mean

**Comment by Pebaz** [comment]
Like:

Start timing:
  For I in range(1000):
    Run func()
End timing()

Instead of just running it once

**Comment by dullbananas** [comment]
sure i'll try that sometime. there also could be something different about my nim script and my cython script that changes execution time

**Comment by dullbananas** [comment]
i think ill try it now

**Comment by dullbananas** [comment]
I just did that and it did not fix the problem. I think it even made it worse.

**Comment by Pebaz** [comment]
That's unfortunate for Nim! ;)
Thanks for running the test.
